In [1]:
from PrepareOriginalData import PrepareData
import numpy as np

# Some constants
taskType = 'all'
data_amount = 1
epochs = 500

# Train on only one question type
question_type = 'yes/no'

# Load training set
p = PrepareData(path_images='data_vqa_feat', # Path to image features 
                subset='train2014', # Desired subset: either train2014 or val2014
                taskType=taskType, # 'OpenEnded', 'MultipleChoice', 'all'
                cut_data=data_amount, # Percentage of data to use, 1 = All values, above 1=#samples for debugging
                output_path='data', # Path where we want to output temporary data
                pad_length=32, # Number of words in a question (zero padded)
                question_threshold=0, answer_threshold=10, # Keep only most common words
                answers_sparse=True, questions_sparse=True, answer_type=question_type)
image_features, questions, answers, annotations = p.load_data()
print("Image features", image_features.shape)
print("Question features", questions.shape)
print("Answers", answers.shape)
print("Dictionary size", p.dic_size)
print("Number of possible classes", np.max(answers) + 1)

# Save dictionary
p.dumpDictionary('dictionary_yes_no')

Using TensorFlow backend.


loading VQA annotations and questions into memory...
0:00:07.144739
creating index...
index created!
loading VQA annotations and questions into memory...
0:00:07.904560
creating index...
index created!
Image features (190604, 1024)
Question features (190604, 32)
Answers (190604, 1)
Dictionary size 10867
Number of possible classes 3


In [2]:
#there should only be yes and no...
p._int_to_answer

{0: 'T.o.P!', 1: 'no', 2: 'yes'}

In [ ]:
from NeuralNetworkYesNo import NeuralNetwork
# Use this when using sparse representation np.max(answers)+1
neuralnet = NeuralNetwork(image_features.shape[0],1024,questions.shape[1],p.dic_size, 1, epochs = epochs, batchSize=512, loss='binary_crossentropy')

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
word_input (InputLayer)         (None, 32)           0                                            
__________________________________________________________________________________________________
word_embedding (Embedding)      (None, 32, 32)       347744      word_input[0][0]                 
__________________________________________________________________________________________________
image_input (InputLayer)        (None, 1024)         0                                            
__________________________________________________________________________________________________
flatten_embedding (Flatten)     (None, 1024)         0           word_embedding[0][0]             
__________________________________________________________________________________________________
concatenat

In [ ]:
# Train network
neuralnet.fit(image_features, questions, answers-1)

(190604, 1024) (190604, 32) (190604, 1)
Train on 133422 samples, validate on 57182 samples
Epoch 1/500
133422/133422 [==============================] - 9s 65us/step - loss: 0.6852 - acc: 0.5833 - val_loss: 0.6790 - val_acc: 0.6035
Epoch 2/500
133422/133422 [==============================] - 5s 36us/step - loss: 0.6760 - acc: 0.5993 - val_loss: 0.6751 - val_acc: 0.6035
Epoch 3/500
133422/133422 [==============================] - 5s 35us/step - loss: 0.6737 - acc: 0.6013 - val_loss: 0.6756 - val_acc: 0.6035
Epoch 4/500
133422/133422 [==============================] - 5s 35us/step - loss: 0.6724 - acc: 0.6015 - val_loss: 0.6736 - val_acc: 0.6035
Epoch 5/500
133422/133422 [==============================] - 5s 34us/step - loss: 0.6718 - acc: 0.6017 - val_loss: 0.6706 - val_acc: 0.6035
Epoch 6/500
133422/133422 [==============================] - 5s 34us/step - loss: 0.6701 - acc: 0.6015 - val_loss: 0.6686 - val_acc: 0.6035
Epoch 7/500
133422/133422 [==============================] - 5s 35us/

Epoch 28/500
133422/133422 [==============================] - 5s 35us/step - loss: 0.4825 - acc: 0.7720 - val_loss: 0.5039 - val_acc: 0.7629
Epoch 29/500
133422/133422 [==============================] - 5s 35us/step - loss: 0.4761 - acc: 0.7757 - val_loss: 0.4880 - val_acc: 0.7705
Epoch 30/500
133422/133422 [==============================] - 5s 36us/step - loss: 0.4681 - acc: 0.7801 - val_loss: 0.4865 - val_acc: 0.7748
Epoch 31/500
133422/133422 [==============================] - 5s 35us/step - loss: 0.4619 - acc: 0.7842 - val_loss: 0.4705 - val_acc: 0.7809
Epoch 32/500
133422/133422 [==============================] - 5s 36us/step - loss: 0.4546 - acc: 0.7899 - val_loss: 0.4678 - val_acc: 0.7854
Epoch 33/500
133422/133422 [==============================] - 5s 35us/step - loss: 0.4474 - acc: 0.7943 - val_loss: 0.4564 - val_acc: 0.7907
Epoch 34/500
133422/133422 [==============================] - 5s 36us/step - loss: 0.4378 - acc: 0.7987 - val_loss: 0.4498 - val_acc: 0.7956
Epoch 35/500


Epoch 54/500
133422/133422 [==============================] - 5s 36us/step - loss: 0.3154 - acc: 0.8628 - val_loss: 0.3036 - val_acc: 0.8765
Epoch 55/500
133422/133422 [==============================] - 5s 38us/step - loss: 0.3105 - acc: 0.8657 - val_loss: 0.2932 - val_acc: 0.8783
Epoch 56/500
133422/133422 [==============================] - 5s 35us/step - loss: 0.3047 - acc: 0.8672 - val_loss: 0.2935 - val_acc: 0.8786
Epoch 57/500
133422/133422 [==============================] - 5s 35us/step - loss: 0.2996 - acc: 0.8704 - val_loss: 0.2822 - val_acc: 0.8849
Epoch 58/500
133422/133422 [==============================] - 5s 35us/step - loss: 0.2969 - acc: 0.8706 - val_loss: 0.2799 - val_acc: 0.8835
Epoch 59/500
133422/133422 [==============================] - 5s 35us/step - loss: 0.2930 - acc: 0.8736 - val_loss: 0.2723 - val_acc: 0.8885
Epoch 60/500
133422/133422 [==============================] - 5s 37us/step - loss: 0.2887 - acc: 0.8754 - val_loss: 0.2642 - val_acc: 0.8916
Epoch 61/500


133422/133422 [==============================] - 5s 38us/step - loss: 0.2255 - acc: 0.9041 - val_loss: 0.1855 - val_acc: 0.9276
Epoch 81/500
133422/133422 [==============================] - 4s 34us/step - loss: 0.2220 - acc: 0.9057 - val_loss: 0.1854 - val_acc: 0.9260
Epoch 82/500
133422/133422 [==============================] - 5s 37us/step - loss: 0.2225 - acc: 0.9046 - val_loss: 0.1749 - val_acc: 0.9307
Epoch 83/500
133422/133422 [==============================] - 5s 35us/step - loss: 0.2176 - acc: 0.9077 - val_loss: 0.1796 - val_acc: 0.9316
Epoch 84/500
133422/133422 [==============================] - 5s 35us/step - loss: 0.2177 - acc: 0.9077 - val_loss: 0.1704 - val_acc: 0.9324
Epoch 85/500
133422/133422 [==============================] - 5s 35us/step - loss: 0.2119 - acc: 0.9097 - val_loss: 0.1728 - val_acc: 0.9312
Epoch 86/500
133422/133422 [==============================] - 5s 35us/step - loss: 0.2113 - acc: 0.9101 - val_loss: 0.1631 - val_acc: 0.9348
Epoch 87/500
133422/133422

Epoch 108/500
133422/133422 [==============================] - 5s 34us/step - loss: 0.1710 - acc: 0.9279 - val_loss: 0.1191 - val_acc: 0.9532
Epoch 109/500
133422/133422 [==============================] - 5s 34us/step - loss: 0.1696 - acc: 0.9288 - val_loss: 0.1181 - val_acc: 0.9541
Epoch 110/500
133422/133422 [==============================] - 5s 34us/step - loss: 0.1707 - acc: 0.9284 - val_loss: 0.1171 - val_acc: 0.9556
Epoch 111/500
133422/133422 [==============================] - 5s 34us/step - loss: 0.1680 - acc: 0.9291 - val_loss: 0.1127 - val_acc: 0.9578
Epoch 112/500
133422/133422 [==============================] - 4s 34us/step - loss: 0.1676 - acc: 0.9296 - val_loss: 0.1155 - val_acc: 0.9546
Epoch 113/500
133422/133422 [==============================] - 4s 34us/step - loss: 0.1654 - acc: 0.9311 - val_loss: 0.1080 - val_acc: 0.9572
Epoch 114/500
133422/133422 [==============================] - 5s 34us/step - loss: 0.1634 - acc: 0.9312 - val_loss: 0.1160 - val_acc: 0.9556
Epoch 

133422/133422 [==============================] - 5s 34us/step - loss: 0.1383 - acc: 0.9421 - val_loss: 0.0834 - val_acc: 0.9691
Epoch 136/500
133422/133422 [==============================] - 4s 33us/step - loss: 0.1395 - acc: 0.9426 - val_loss: 0.0868 - val_acc: 0.9670
Epoch 137/500
133422/133422 [==============================] - 4s 34us/step - loss: 0.1366 - acc: 0.9437 - val_loss: 0.0868 - val_acc: 0.9671
Epoch 138/500
133422/133422 [==============================] - 5s 34us/step - loss: 0.1360 - acc: 0.9440 - val_loss: 0.0823 - val_acc: 0.9682
Epoch 139/500
133422/133422 [==============================] - 5s 34us/step - loss: 0.1364 - acc: 0.9432 - val_loss: 0.0837 - val_acc: 0.9699
Epoch 140/500
133422/133422 [==============================] - 5s 34us/step - loss: 0.1348 - acc: 0.9437 - val_loss: 0.0801 - val_acc: 0.9700
Epoch 141/500
133422/133422 [==============================] - 4s 34us/step - loss: 0.1327 - acc: 0.9450 - val_loss: 0.0804 - val_acc: 0.9698
Epoch 142/500
133422

Epoch 163/500
133422/133422 [==============================] - 5s 34us/step - loss: 0.1169 - acc: 0.9518 - val_loss: 0.0638 - val_acc: 0.9771
Epoch 164/500
133422/133422 [==============================] - 4s 34us/step - loss: 0.1136 - acc: 0.9536 - val_loss: 0.0639 - val_acc: 0.9758
Epoch 165/500
133422/133422 [==============================] - 4s 34us/step - loss: 0.1154 - acc: 0.9534 - val_loss: 0.0633 - val_acc: 0.9769
Epoch 166/500
133422/133422 [==============================] - 4s 33us/step - loss: 0.1141 - acc: 0.9533 - val_loss: 0.0620 - val_acc: 0.9768
Epoch 167/500
133422/133422 [==============================] - 4s 33us/step - loss: 0.1146 - acc: 0.9531 - val_loss: 0.0630 - val_acc: 0.9769
Epoch 168/500
133422/133422 [==============================] - 5s 34us/step - loss: 0.1134 - acc: 0.9538 - val_loss: 0.0594 - val_acc: 0.9785
Epoch 169/500
133422/133422 [==============================] - 4s 34us/step - loss: 0.1114 - acc: 0.9550 - val_loss: 0.0619 - val_acc: 0.9781
Epoch 

Epoch 192/500
133422/133422 [==============================] - 5s 35us/step - loss: 0.0960 - acc: 0.9615 - val_loss: 0.0454 - val_acc: 0.9848
Epoch 193/500
133422/133422 [==============================] - 5s 35us/step - loss: 0.0968 - acc: 0.9609 - val_loss: 0.0473 - val_acc: 0.9837
Epoch 194/500
133422/133422 [==============================] - 5s 34us/step - loss: 0.0935 - acc: 0.9624 - val_loss: 0.0442 - val_acc: 0.9838
Epoch 195/500
133422/133422 [==============================] - 5s 35us/step - loss: 0.0939 - acc: 0.9618 - val_loss: 0.0474 - val_acc: 0.9834
Epoch 196/500
133422/133422 [==============================] - 5s 36us/step - loss: 0.0942 - acc: 0.9629 - val_loss: 0.0439 - val_acc: 0.9844
Epoch 197/500
133422/133422 [==============================] - 5s 34us/step - loss: 0.0929 - acc: 0.9624 - val_loss: 0.0429 - val_acc: 0.9844
Epoch 198/500
133422/133422 [==============================] - 5s 35us/step - loss: 0.0936 - acc: 0.9628 - val_loss: 0.0443 - val_acc: 0.9845
Epoch 

Epoch 222/500
133422/133422 [==============================] - 5s 35us/step - loss: 0.0806 - acc: 0.9679 - val_loss: 0.0353 - val_acc: 0.9885
Epoch 223/500
133422/133422 [==============================] - 5s 35us/step - loss: 0.0814 - acc: 0.9679 - val_loss: 0.0359 - val_acc: 0.9885
Epoch 224/500
133422/133422 [==============================] - 5s 34us/step - loss: 0.0799 - acc: 0.9678 - val_loss: 0.0353 - val_acc: 0.9884
Epoch 225/500
133422/133422 [==============================] - 5s 35us/step - loss: 0.0797 - acc: 0.9679 - val_loss: 0.0329 - val_acc: 0.9890
Epoch 226/500
133422/133422 [==============================] - 5s 35us/step - loss: 0.0791 - acc: 0.9689 - val_loss: 0.0334 - val_acc: 0.9887
Epoch 227/500
133422/133422 [==============================] - 5s 35us/step - loss: 0.0774 - acc: 0.9691 - val_loss: 0.0338 - val_acc: 0.9890
Epoch 228/500
133422/133422 [==============================] - 5s 36us/step - loss: 0.0783 - acc: 0.9688 - val_loss: 0.0335 - val_acc: 0.9895
Epoch 

Epoch 251/500
133422/133422 [==============================] - 4s 33us/step - loss: 0.0722 - acc: 0.9715 - val_loss: 0.0281 - val_acc: 0.9909
Epoch 252/500
133422/133422 [==============================] - 5s 34us/step - loss: 0.0686 - acc: 0.9731 - val_loss: 0.0265 - val_acc: 0.9916
Epoch 253/500
133422/133422 [==============================] - 4s 34us/step - loss: 0.0692 - acc: 0.9730 - val_loss: 0.0274 - val_acc: 0.9914
Epoch 254/500
133422/133422 [==============================] - 5s 34us/step - loss: 0.0686 - acc: 0.9730 - val_loss: 0.0271 - val_acc: 0.9917
Epoch 255/500
133422/133422 [==============================] - 5s 34us/step - loss: 0.0668 - acc: 0.9735 - val_loss: 0.0248 - val_acc: 0.9921
Epoch 256/500
133422/133422 [==============================] - 5s 34us/step - loss: 0.0664 - acc: 0.9742 - val_loss: 0.0249 - val_acc: 0.9923
Epoch 257/500
133422/133422 [==============================] - 4s 34us/step - loss: 0.0687 - acc: 0.9736 - val_loss: 0.0253 - val_acc: 0.9920
Epoch 

Epoch 280/500
133422/133422 [==============================] - 5s 34us/step - loss: 0.0610 - acc: 0.9769 - val_loss: 0.0223 - val_acc: 0.9934
Epoch 281/500
133422/133422 [==============================] - 4s 34us/step - loss: 0.0630 - acc: 0.9754 - val_loss: 0.0224 - val_acc: 0.9930
Epoch 282/500
133422/133422 [==============================] - 4s 34us/step - loss: 0.0601 - acc: 0.9763 - val_loss: 0.0217 - val_acc: 0.9930
Epoch 283/500
133422/133422 [==============================] - 5s 34us/step - loss: 0.0622 - acc: 0.9754 - val_loss: 0.0202 - val_acc: 0.9939
Epoch 284/500
133422/133422 [==============================] - 4s 34us/step - loss: 0.0611 - acc: 0.9762 - val_loss: 0.0210 - val_acc: 0.9936
Epoch 285/500
133422/133422 [==============================] - 5s 34us/step - loss: 0.0626 - acc: 0.9759 - val_loss: 0.0200 - val_acc: 0.9939
Epoch 286/500
133422/133422 [==============================] - 4s 34us/step - loss: 0.0594 - acc: 0.9771 - val_loss: 0.0209 - val_acc: 0.9935
Epoch 

133422/133422 [==============================] - 4s 33us/step - loss: 0.0513 - acc: 0.9805 - val_loss: 0.0154 - val_acc: 0.9954
Epoch 310/500
133422/133422 [==============================] - 4s 33us/step - loss: 0.0535 - acc: 0.9791 - val_loss: 0.0161 - val_acc: 0.9950
Epoch 311/500
133422/133422 [==============================] - 4s 33us/step - loss: 0.0529 - acc: 0.9793 - val_loss: 0.0152 - val_acc: 0.9953
Epoch 312/500
133422/133422 [==============================] - 4s 34us/step - loss: 0.0513 - acc: 0.9802 - val_loss: 0.0145 - val_acc: 0.9957
Epoch 313/500
133422/133422 [==============================] - 4s 33us/step - loss: 0.0516 - acc: 0.9800 - val_loss: 0.0155 - val_acc: 0.9953
Epoch 314/500
133422/133422 [==============================] - 5s 34us/step - loss: 0.0512 - acc: 0.9806 - val_loss: 0.0146 - val_acc: 0.9959
Epoch 315/500
133422/133422 [==============================] - 5s 35us/step - loss: 0.0504 - acc: 0.9809 - val_loss: 0.0156 - val_acc: 0.9952
Epoch 316/500
133422

133422/133422 [==============================] - 5s 36us/step - loss: 0.0432 - acc: 0.9835 - val_loss: 0.0115 - val_acc: 0.9968
Epoch 340/500
133422/133422 [==============================] - 5s 37us/step - loss: 0.0429 - acc: 0.9835 - val_loss: 0.0112 - val_acc: 0.9966
Epoch 341/500
133422/133422 [==============================] - 5s 37us/step - loss: 0.0425 - acc: 0.9839 - val_loss: 0.0112 - val_acc: 0.9967
Epoch 342/500
133422/133422 [==============================] - 5s 38us/step - loss: 0.0439 - acc: 0.9833 - val_loss: 0.0120 - val_acc: 0.9963
Epoch 343/500
133422/133422 [==============================] - 5s 37us/step - loss: 0.0426 - acc: 0.9832 - val_loss: 0.0113 - val_acc: 0.9965
Epoch 344/500
133422/133422 [==============================] - 5s 38us/step - loss: 0.0419 - acc: 0.9842 - val_loss: 0.0103 - val_acc: 0.9970
Epoch 345/500
 87040/133422 [==================>...........] - ETA: 1s - loss: 0.0429 - acc: 0.9834

In [9]:
#see what it predicts on training data, on which it trained!
predTrain = neuralnet.predict_current_state(image_features, questions)
print(predTrain)
import numpy
#pred = numpy.argmax(predTrain, axis=1)
pred = numpy.round(predTrain)+1
print(pred)
print(answers)
from sklearn.metrics import accuracy_score
# TODO: can probably still improve this accuracy
print('Answer type classification accuracy:', accuracy_score(pred, answers))

[[  9.98969316e-01]
 [  2.68568856e-09]
 [  5.26025426e-04]
 ..., 
 [  2.90180822e-08]
 [  8.47338408e-04]
 [  1.23870624e-02]]
[[ 1.]
 [ 0.]
 [ 0.]
 ..., 
 [ 0.]
 [ 0.]
 [ 0.]]
[[2]
 [1]
 [1]
 ..., 
 [1]
 [1]
 [1]]
Answer type classification accuracy: 0.972225136933


In [10]:
image_features = questions = answers = annotations = []
question_type = 'yes/no'
# Load validation set and evaluate prediction on it
pt= PrepareData(path_images='data_vqa_feat', # Path to image features 
                        subset='val2014', # Desired subset: either train2014 or val2014
                        taskType=taskType, # 'OpenEnded', 'MultipleChoice', 'all'
                        cut_data=data_amount, # Percentage of data to use, 1 = All values, above 1 = 10 samples for debugging
                        output_path='data', # Path where we want to output temporary data
                        pad_length=32, # Number of words in a question (zero padded)
                        question_threshold=0, answer_threshold=10, # Keep only most common words
                        answers_sparse=True, questions_sparse=True, answer_type=question_type,
                        precomputed_dic=p._question_dict)
pt.loadDictionary('data/dictionary_yes_no.pkl') # Use same dictionary as in training
image_features, questions, answers, annotations = pt.load_data()
print("Image features", image_features.shape)
print("Question features", questions.shape)
print("Dictionary size", pt.dic_size)

loading VQA annotations and questions into memory...
0:00:02.525527
creating index...
index created!
loading VQA annotations and questions into memory...
0:00:03.589358
creating index...
index created!
Image features (90956, 1024)
Question features (90956, 32)
Dictionary size 10867


In [13]:
# Predict
pred = neuralnet.predict_current_state(image_features, questions)
import numpy
#pred = numpy.argmax(pred, axis=1)
pred = numpy.round(pred)+1
pred

array([[ 2.],
       [ 2.],
       [ 2.],
       ..., 
       [ 1.],
       [ 2.],
       [ 2.]], dtype=float32)

In [14]:
from sklearn.metrics import accuracy_score
# TODO: can probably still improve this accuracy
print('Answer type classification accuracy:', accuracy_score(pred, answers))

Answer type classification accuracy: 0.636351642552
